### ISSUE TITLE
Birthday redesign

### ISSUE THREAD

**Issue by simonw** [simonw/simonwillisonblog#438]
Blog is 22 years old today!

The sidebar is no longer working now that I write longer blogmark entries (inspired by https://daringfireball.net/ ):

![CleanShot 2024-06-12 at 12 36 33@2x](https://github.com/simonw/simonwillisonblog/assets/9599/c785539f-c3d3-422e-a309-aec600b587fd)

New design for homepage: mixed content on the left, links to long-form blog entries on the right.

**Comment by simonw** [comment]
Blogged about this here: https://simonwillison.net/2024/Jun/12/homepage-redesign/

**Comment by lambrospetrou** [comment]
There is a typo in `The right hand column on my homepage now displays entries, quotations and blogmarks as a combined list`, it should be `The LEFT hand column` :) 

Love your website content!!!

**Comment by Marat-Tanalin** [comment]
Consider improving semantics by making the first-level heading on the page of each article the true first-level heading — `h1` — instead of the logo wrongly being semantic `h1` on each page instead of only being `h1` on the home page, and the first-level heading wrongly marked-up as second-level heading `h2`. ;-) The logo can only sematically be `h1` on homepage. On other pages, it should not even be a heading, `strong` is enough to make it somewhat special semantically.
